inherit_from: .rubocop_todo.yml

inherit_gem:
  rswag-specs: .rubocop_rspec_alias_config.yml

plugins:
  - rubocop-rspec
  - rubocop-rails
require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: true
  Exclude:
    - 'app/config/application.rb'
    - 'app/mailers/**/*.rb'
    - 'app/serializers/**/*.rb'
    - 'db/migrate/**/*.rb'
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: "double_quotes"

# API Docs

RSpec/NestedGroups:
  Enabled: true
  Exclude:
    - 'spec/**/*_doc_spec.rb'
