# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "~> 4.0.0"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use PostgreSQL as the database for Active Record
gem "pg"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 7.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
gem "redis"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[jruby windows]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Views and components
gem "dsfr-assets"
gem "dsfr-view-components"
gem "view_component", "~> 3.19"

# Mon Devis Sans Oublis custom gems
gem "active_model_serializers"
gem "active_storage-postgresql" # Store file in database
# gem "active_storage-postgresql", github: "shayonj/active_storage-postgresql", branch: "s/rails-7"
gem "active_storage_validations" # Validate ActiveStorage attachments
gem "brevo", require: false # Brevo (ex Sendinblue) API
gem "committee" # Parse OpenAPI 3 generated by rswag to validate requests/responses
gem "diff-lcs", require: false
gem "good_job" # Postgres-backed job queue
gem "rswag-api" # Serves the generated Swagger documentation
gem "rswag-ui" # Provides the Swagger UI interface
gem "strip_attributes"

# Quote files Reading
gem "fuzzy-string-match", require: false
gem "mime-types", require: false
gem "mini_magick", require: false
gem "pdf-reader", require: false
# gem "rtesseract", require: false

gem "rnt", path: "lib/rnt"

# Efficiency
gem "concurrent-ruby", require: false
gem "dotenv_validator"
gem "parallel", require: false

# Required for langchainrb LLMs
gem "csv" # Since Ruby > 3.4.0
gem "faraday", ">= 2.14.1"
gem "faraday-follow_redirects"
gem "langchainrb", ">= 0.19" # Framework around LLMs
gem "ruby_llm", ">= 1.10.0", require: false

gem "clamby", require: false # Virus scanning with ClamAV
gem "ostruct" # Since Ruby > 3.4.0
gem "rack-attack" # Rate limiting
gem "rack-cors" # TODO: use built-in Rails 8+ https://www.bigbinary.com/blog/rails-8-rate-limiting-api

# Back Office
gem "activeadmin"
gem "omniauth-proconnect" # ProConnect SSO
gem "omniauth-rails_csrf_protection" # CSRF protection for OmniAuth when used without Devise
gem "sassc-rails"

group :development, :test do
  gem "brakeman"
  gem "bundler-audit"
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[mri windows]
  gem "dotenv-rails"
  gem "factory_bot_rails"
  gem "flog", "~> 4.8.0", require: false # Avoid /usr/local/bundle/gems/flog-4.9.1/lib/flog.rb:237:in 'Flog#initialize': can't modify frozen Hash: {all: true, continue: true, methods: true} (FrozenError) # rubocop:disable Layout/LineLength
  gem "foreman"
  gem "openapi3_parser", require: false
  gem "rspec-rails"
  gem "rswag-specs" # Allows API documentation via specs
  gem "rubycritic", require: false
end

group :test do
  gem "capybara"
  gem "cucumber-rails", require: false # , "~> 3.0"
  gem "database_cleaner"
  gem "faker", require: false
  gem "guard"
  gem "guard-cucumber"
  gem "guard-rspec"
  gem "rspec"
  gem "rubocop"
  gem "rubocop-capybara"
  gem "rubocop-factory_bot"
  gem "rubocop-performance"
  gem "rubocop-rails"
  gem "rubocop-rake"
  gem "rubocop-rspec"
  gem "rubocop-rspec_rails"
  gem "vcr"
  gem "webmock" # Required to intercept HTTP requests
end

group :development do
  # gem "bundler-stats" # TODO: re-enable when compatible with bundler > 2.4
  gem "licensed" # Requires native cmake and pkg-config libraries for rugged gem dependency
  gem "memory_profiler"
  gem "next_rails"
  gem "rails_best_practices"
  gem "rails-erd"
  gem "rails_stats"
  gem "rugged" # For licensed on Github Actions CI

  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :production do
  # Monitoring and error reporting
  gem "sentry-rails"
  gem "sentry-ruby"
end
